name: Build Kivy APK

on:
  push:
    branches:
      - main  # Change this if your default branch is different
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu to run Buildozer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Get the source code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Compatible with Buildozer

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk autoconf automake cmake libtool pkg-config zlib1g-dev python3-venv

      - name: Install Buildozer & Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install cython virtualenv
          pip install buildozer
          buildozer init  # Create buildozer.spec if not already present

      - name: Build APK
        run: |
          source venv/bin/activate
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Kivy-APK
          path: bin/*.apk
